### PR TITLE
Scroll to top issue resolved

### PR DESCRIPTION
**Pull request by codemaniac-sahil**
Hey, @shelcia I tried to resolve the scroll to top issue. Please check.

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
@shelcia, would you please merge this branch.

**Comment by shelcia** [comment]
@codemaniac-sahil  have reviewed and added comments Please resolve it

**Comment by codemaniac-sahil** [comment]
@shelcia, would you please tell me what are you trying to say. I am no getting it.

**Comment by shelcia** [comment]
> @shelcia, would you please tell me what are you trying to say. I am no getting it.

Add your styling in .scss file not directly into css. These are sass file which are to be compiled into css

**Comment by codemaniac-sahil** [comment]
Okay @shelcia

**Comment by codemaniac-sahil** [comment]
@shelcia, It is done. Would you please check.

**Comment by codemaniac-sahil** [comment]
@shelcia, I have done some changes. Please check.

**Comment by shelcia** [comment]
Screenshot 2023-02-13 at 7 23 02 PM
Screenshot 2023-02-13 at 7 23 15 PM
TEST IS OVERLAPPING in your commit

**Comment by codemaniac-sahil** [comment]
@shelcia, Okay, I am working on it.

**Comment by codemaniac-sahil** [comment]
@shelcia, Please check my new commit, I resolved the issue which is mentioned above.

**Comment by shelcia** [comment]
The code is redundant. Please create the component in one file and utilise whenever needed

**Comment by shelcia** [comment]
Remove the border, icon should be moved parallel to theme icon. Style the icons similar to theme toggle button.

Screenshot 2023-02-18 at 7 33 02 PM

**Comment by codemaniac-sahil** [comment]
@shelcia, okay I am working on it.

**Comment by codemaniac-sahil** [comment]
@shelcia, Please check my new commit
Screenshot from 2023-02-20 18-01-14

**Review by shelcia — APPROVED** [review]

**Pull request merged**
