### PR TITLE
 issue #260: fixed overlapping of text with the image.

### PR DESCRIPTION
**Pull request by chikkibum**
hey @shelcia Following changes were made.

added `justify-content:space-evenly` and changed `margin-left:-30px;` in  `.row` in `src/styles/argon.css` and now the final result looks like this .

fixed but centered

also here is a video attached:

https://user-images.githubusercontent.com/71315985/216386838-c1abbdbd-e914-42de-a8d9-723baee36604.mp4

### CODE REVIEW

**Comment by shelcia** [comment]
this will affect all the styling. Please add in such a way that it only affects them.

**Comment by chikkibum** [comment]
hey @shelcia i have reverted previous changes and changed `margin-left--50px;` in the `img-align` selector.

here is a attached video :-

https://user-images.githubusercontent.com/71315985/216676986-da5d6082-1bbb-4f72-9718-1e6849c1134f.mp4

**Comment by shelcia** [comment]
Hi @chikkibum alter css in such a way that it will only impact that particular section in template 1

**Comment by chikkibum** [comment]
hey @shelcia if you could give me some hints then it would be great.

**Comment by chikkibum** [comment]
hey @shelcia I think the changes I made are only affecting template 1. 
could you further explain what the issue is here.

**Review by shelcia — APPROVED** [review]

**Comment by shelcia** [comment]
solved issue #260

**Pull request merged**
