### PR TITLE
fixed responsiveness  of login

### LINKED ISSUE #323: Login tab is not aligned properly
Screenshot_20240113-015236
Please assign me this under iwoc

### PR DESCRIPTION
**Pull request by NaveenChandraAdhikari**
Closes #323 

fixed responsiveness by adding some media queries

### CODE REVIEW

**Comment by shelcia** [comment]
could you please verify the PR

**Comment by NaveenChandraAdhikari** [comment]
> could you please verify the PR



sorry I'm kinda new to Open Source can you please tell me how to approve it

**Review by NaveenChandraAdhikari — COMMENTED** [review]
I have fixed  responsiveness and alignment issue  of login btn,I have added media query for that in the code .

**Review by shelcia — CHANGES_REQUESTED** [review]
make changes in this https://github.com/shelcia/dynamic-portfolio/blob/master/src/styles/style.scss and compile , it should compile and style.css

**Comment by NaveenChandraAdhikari** [comment]
> make changes in this https://github.com/shelcia/dynamic-portfolio/blob/master/src/styles/style.scss and compile , it should compile and style.css

is it not argon.css

**Comment by shelcia** [comment]
nope

**Pull request closed without merging**
